package main

import (
	"budget4home/src/config"
	"budget4home/src/expense"
	"budget4home/src/label"
	"os"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "budget4home/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title budget4home API
// @version 1.0
// @description Project to control budget for home

// @host localhost:5000
// @BasePath /api

func main() {
	db := config.PrepareDb()

	r := gin.Default()
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	api := r.Group("/api")

	{ // labels
		repo := label.NewRepository(db)
		service := label.NewService(repo)
		label.NewController(api, service)
	}

	{ // expenses
		expense.NewController(api)
	}

	if len(os.Getenv("PORT")) == 0 {
		// set default port
		os.Setenv("PORT", "5000")
	}
	r.Run(":" + os.Getenv("PORT"))
}
